#!/usr/bin/env python3
"""Full-prefix detection curves for the temperature-matched regeneration.

Both arms of every cell here were generated by
:mod:`generate_temperature_matched` at a *common* temperature, so the entropy
confound that contaminates the released pair cannot operate.  This command
recomputes each rule at every prefix length rather than at the four horizons
:mod:`analyse_temperature_matched` reports, and writes

* ``temperature_prefix_curves.csv`` -- every (model, temperature, rule, prefix)
  cell with its Type I and Type II rate and the binomial MCSE of each;
* ``prefix_curves_matched_<model>.pdf`` -- one temperature panel per facet,
  Type II against prefix length;
* ``temperature_sweep_matched.pdf`` -- Type II against temperature at a fixed
  horizon, which is where the discriminating region is legible.

Calibration.  This describes what the code does now; it used to say split-half,
which the code stopped doing.  Type II uses a 5% cutoff taken at each prefix from
the WHOLE unwatermarked arm, without using watermarked scores. The arms remain
paired by prompt; this is not a claim of statistical independence. In the
absence of ties at the cutoff, rules have the same realised calibration size.
With a split-half cutoff from 250 calibration documents the realised level has
standard deviation about .02, which induces a Type II standard deviation near .03,
larger than the differences between the leading rules.  Type I is cross-fitted
over ``CROSS_FIT_FOLDS`` folds instead, so it uses every document without being
calibrated on the one it scores.  The split-half spread is still recorded, as the
quantity the earlier design was drawing from.

No model weights or GPU are used; this reads the generated ``.npz`` arrays.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import sys
from pathlib import Path
from typing import Callable, Mapping, Sequence

import numpy as np

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "code"))

import benchmark_paper_experiment as benchmark  # noqa: E402
import deficit_hierarchy as dh
import dirichlet_detector as dd  # noqa: E402
import real_data_experiment as real  # noqa: E402
import trgof  # noqa: E402
import matched_data_loader as matched


def arm_arrays(path, *, allow_legacy=False) -> dict:
    """Validated single-archive compatibility API; use load_cells for pairing."""
    return matched.read_archive(path, allow_legacy=allow_legacy).arrays

# The generated arms live in the repository, not in a session scratch
# directory: the base arms in temperature_matched/ and the documents past 500
# in its extension/ subdirectory, alongside the extended prompt tables.  This
# used to default to an ephemeral /private/tmp path, which meant the 2500
# document results could not be reproduced from a clone.  WM_SCRATCH still
# overrides it for runs that generate fresh arms elsewhere.
SCRATCH = Path(os.environ.get(
    "WM_SCRATCH",
    REPO / "results/bayesian_paper_benchmark/real_model/temperature_matched",
))
DEFAULT_OUTPUT_DIR = (
    REPO / "results/bayesian_paper_benchmark/real_model/temperature_matched"
)

MODEL_VOCAB = {"1p3B": 50272, "2p7B": 32000}
DISPLAY_MODEL = {"1p3B": "OPT-1.3B", "2p7B": "Sheared-LLaMA-2.7B"}
LEVEL = 0.05
SUMMARY_HORIZON = 100

# Rule identity is pinned here.  Colour, dash and label all key off this order,
# so adding a rule appends rather than recolouring the existing curves.  The
# five hues are Okabe-Ito blue/vermillion/reddish-purple plus two dark steps;
# the set was chosen by maximising the minimum pairwise OKLab dE under
# protanopic, deuteranopic and tritanopic simulation (Machado et al. 2009).
# Worst pair: dE 8.6 simulated, 16.4 normal vision -- both above threshold.
# Dash patterns repeat the distinction so identity is never colour-alone.
# Nine curves cannot take nine hues and stay legible under colour-vision
# deficiency, so identity is COMPOSITE: hue names the family, dash names the
# member within it.  That also serves the argument -- the three tunings of the
# least-favorable score read as one band whose width is the tuning sensitivity,
# rather than as three unrelated curves.  The four hues are Okabe-Ito
# blue/purple/vermillion/green, whose worst pair is dE 8.6 simulated and 16.4
# at normal vision, both above threshold.
RULE_STYLE: tuple[tuple[str, str, str, tuple], ...] = (
    # Bayesian rules
    ("bayes_uniontail_w0.5", "Bayes, shared $\\Delta$ + union tail", "#0B6FA4", ()),
    ("bayes_shared",         "Bayes, shared $\\Delta$",      "#542788", (5, 1.5)),
    # reference scores
    ("h_ars",           "$h_{\\mathrm{ars}}$",                "#D55E00", ()),
    ("h_log",           "$h_{\\mathrm{log}}$",                "#D55E00", (2.5, 1.5)),
    ("h_ind_1_over_e",  "$h_{\\mathrm{ind},1/e}$",            "#D55E00", (1, 1.4)),
    # the least-favorable family, one hue and three dashes
    ("h_gum_star_0.1",  "$h^\\star_{\\mathrm{gum},.1}$",      "#009E73", ()),
    ("h_gum_star_0.01", "$h^\\star_{\\mathrm{gum},.01}$",     "#009E73", (3.5, 1.2)),
    ("h_gum_star_0.005","$h^\\star_{\\mathrm{gum},.005}$",    "#009E73", (1.2, 1.2)),
    ("trgof_s2",        "Tr-GoF ($s=2$)",                    "#9B2226", (6, 1.5, 1, 1.5)),
)
# The union-tail weight sweep.  w=1 is tail shape only (the Dirichlet layer at
# full width), w=0 is tail width only (alpha=inf over the width ladder); both
# are exact sub-models of the union, so they share one implementation.
UNION_WEIGHTS: tuple[float, ...] = (0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0)

# The deficit prior is Unif(DELTA_LOW, DELTA_HIGH).  The upper limit is one
# half, which is where the designated leading coordinate stops being the
# largest: at tail width J the residual coordinates each carry Delta/J, so
# 1-Delta is the maximum only while Delta <= J/(1+J).
DELTA_LOW = 0.001
DELTA_HIGH = 0.5
# The sensitivity arm of tab:deficit-support: a deficit prior carried up to
# almost one, where the "deficit" no longer names a small departure.
WIDE_DELTA_HIGH = 0.999
UNION_RULE_LABEL = {
    0.0: "tail width only ($w=0$)",
    1.0: "tail shape only ($w=1$)",
}
UNION_RULE_LABEL.update({
    w: f"union tail, $w={w:g}$".replace("=0.", "=.")
    for w in UNION_WEIGHTS if w not in (0.0, 1.0)
})
# The displayed w=.5 rule uses the same name as the synthetic and released
# figures; their captions specify its equal-weight union-tail prior.
UNION_RULE_LABEL[0.5] = r"Bayes, shared $\Delta$ + union tail"


def union_rule_name(weight: float) -> str:
    return f"bayes_uniontail_w{weight:g}"


# Everything scored is now drawn, so this is empty; it stays as the hook for
# a rule that is computed but deliberately not plotted.
EXTRA_REFERENCE_RULES: tuple[tuple[str, str], ...] = ()

# The inverse-transform menu.  There is deliberately no union-tail or Dirichlet
# entry: those layers model the residual next-token mass, which the inverse
# working alternative does not resolve, so they have no inverse counterpart.
# Colours reuse the same validated six (worst pair dE 8.6 simulated, 16.4
# normal), reassigned by rule.
INVERSE_RULE_STYLE: tuple[tuple[str, str, str, tuple], ...] = (
    ("bayes_shared_inv", "Bayes, shared $\\Delta$",              "#0B6FA4", ()),
    ("h_neg",            "$h_{\\mathrm{neg}}$",                   "#D55E00", (2.5, 1.5)),
    ("h_dif_star_0.1",   "$h^{*}_{\\mathrm{dif},.1}$",            "#009E73", (3.5, 1.2, 1, 1.2)),
    ("h_dif_star_0.01",  "$h^{*}_{\\mathrm{dif},.01}$",           "#542788", (5, 1.5)),
    ("h_dif_star_0.001", "$h^{*}_{\\mathrm{dif},.001}$",          "#CC79A7", (1, 1.4)),
    ("trgof_s2_inv",     "Tr-GoF ($s=2$)",                      "#9B2226", (6, 1.5, 1, 1.5)),
)

RULE_ORDER = tuple(name for name, _, _, _ in RULE_STYLE)
INVERSE_RULE_ORDER = tuple(name for name, _, _, _ in INVERSE_RULE_STYLE)
RULE_LABEL_INV = {name: label for name, label, _, _ in INVERSE_RULE_STYLE}
RULE_COLOR_INV = {name: color for name, _, color, _ in INVERSE_RULE_STYLE}
RULE_DASH_INV = {name: dash for name, _, _, dash in INVERSE_RULE_STYLE}
COMPUTED_RULES = (
    ("bayes_pooled",)
    +
    RULE_ORDER
    + tuple(name for name, _ in EXTRA_REFERENCE_RULES)
    + tuple(union_rule_name(w) for w in UNION_WEIGHTS
            if union_rule_name(w) not in RULE_ORDER)
)
RULE_LABEL = {name: label for name, label, _, _ in RULE_STYLE}
RULE_LABEL.update(dict(EXTRA_REFERENCE_RULES))
RULE_LABEL["bayes_pooled"] = "Bayes, hierarchical $\\Delta$"
RULE_LABEL.update({union_rule_name(w): UNION_RULE_LABEL[w] for w in UNION_WEIGHTS})
RULE_COLOR = {name: color for name, _, color, _ in RULE_STYLE}
RULE_DASH = {name: dash for name, _, _, dash in RULE_STYLE}


def computed_rules(union_weight=None):
    if union_weight is None:
        return COMPUTED_RULES
    if not np.isfinite(union_weight) or not 0 <= union_weight <= 1:
        raise ValueError("union weight must lie in [0,1]")
    selected = union_rule_name(union_weight)
    return tuple(selected if rule == union_rule_name(.5) else rule
                 for rule in COMPUTED_RULES
                 if not rule.startswith("bayes_uniontail_") or rule == union_rule_name(.5))

CURVE_FIELDS = (
    "model", "temperature", "scheme", "tokens_generated", "rule", "prefix",
    "type1", "type1_mcse", "type2", "type2_mcse", "auc",
    "type2_split_half", "type2_split_sd",
    "n_calibration", "n_type1", "n_watermarked",
    "distinct_watermarked", "distinct_null",
)

# Number of random re-splits used to report how much of a Type II difference is
# calibration noise rather than signal.
SPLIT_REPLICATES = 200
CROSS_FIT_FOLDS = 5


def inverse_score_paths(
    name: str, pivots: np.ndarray, grids: Mapping[str, object], vocab: int
) -> np.ndarray:
    """All-prefix scores for the inverse-transform menu.

    ``pivots`` is the formal difference ``d = |U - j/(M-1)|`` for zero-based
    permutation rank ``j``, matching the manuscript's primary convention rather
    than the released generator's shifted ``(j-1)/(M-1)``.
    """
    horizon = pivots.shape[1]
    if name == "h_neg":
        return np.cumsum(-pivots, axis=1)
    if name.startswith("h_dif_star_"):
        return np.cumsum(
            benchmark.paper_inverse_optimal_score(pivots, float(name.rsplit("_", 1)[1])),
            axis=1,
        )
    if name == "trgof_s2_inv":
        p = trgof.inverse_p_values(pivots, vocab)
        return np.column_stack([
            trgof.statistic(p[:, :h]) for h in range(1, horizon + 1)
        ])
    if name == "bayes_shared_inv":
        delta, weights = dd.gauss_legendre_delta_grid(0.001, 0.5, 96)
        return real.shared_spike_paths(
            pivots, scheme="inverse", vocabulary_size=vocab,
            deltas=delta, delta_weights=weights,
            horizons=tuple(range(1, horizon + 1)),
        )
    raise KeyError(name)


def formal_inverse_pivots(uniform: np.ndarray, eta_shifted: np.ndarray, vocab: int) -> np.ndarray:
    """Rebuild ``d = |U - j/(M-1)|`` from the stored shifted eta.

    Generation follows the released ``transform_Y``, which records
    ``eta = (j-1)/(M-1)``.  The integer rank is recovered exactly and the
    zero-based convention reapplied, so the watermarked arm matches the
    convention ``replay_with_key`` already returns for the null arm.  The
    round-trip is checked rather than assumed.
    """
    denominator = vocab - 1.0
    rank_float = np.asarray(eta_shifted, dtype=float) * denominator + 1.0
    rank = np.rint(rank_float)
    if float(np.abs(rank_float - rank).max()) > 0.01:
        raise ValueError("stored inverse eta does not reconstruct integer ranks")
    if np.any((rank < 0) | (rank >= vocab)):
        raise ValueError("reconstructed inverse ranks fall outside 0..M-1")
    return np.abs(np.asarray(uniform, dtype=float) - rank / denominator)


def score_paths(name: str, pivots: np.ndarray, grids: Mapping[str, object]) -> np.ndarray:
    """Return the (documents, prefixes) matrix of scores at every prefix.

    Cumulative rules are accumulated once rather than recomputed per prefix;
    the Bayesian grids return all prefixes from a single pass.  Only Tr-GoF
    needs a per-prefix call, because its statistic re-sorts the p-values.
    """
    horizon = pivots.shape[1]
    if name == "h_ars":
        return np.cumsum(-np.log1p(-np.clip(pivots, 0.0, 1 - 1e-12)), axis=1)
    if name == "h_log":
        return np.cumsum(np.log(np.clip(pivots, 1e-12, 1.0)), axis=1)
    if name == "h_ind_1_over_e":
        return np.cumsum(
            benchmark.gumbel_score(pivots, name, None), axis=1
        )
    if name.startswith("h_gum_star_"):
        return np.cumsum(
            benchmark.paper_gumbel_optimal_score(pivots, float(name.rsplit("_", 1)[1])),
            axis=1,
        )
    if name == "trgof_s2":
        p = trgof.gumbel_p_values(pivots)
        return np.column_stack([
            trgof.statistic(p[:, :h]) for h in range(1, horizon + 1)
        ])
    grid = grids[name]
    clipped = np.clip(pivots, 1e-12, 1 - 1e-12)
    if isinstance(grid, dh.PooledDeficitGrid):
        # Returns the paths directly rather than a (values, maxima) pair.
        return grid.shared_paths(clipped)
    return grid.shared_paths(clipped, horizons=tuple(range(1, horizon + 1)))[0]


def build_grids(vocab: int, union_weight: float | None = None) -> dict[str, object]:
    """Grids for every scored rule.

    One ``UnionTailBayesGrid`` per weight in ``UNION_WEIGHTS``.  The endpoints
    are the parent models: ``w=1`` is the Dirichlet shape prior at full width
    and ``w=0`` the tail-width prior at ``alpha=inf``.  ``union_weight``, when
    given, overrides the sweep with a single grid at that weight, which is how
    the earlier one-weight runs were produced.
    """
    computed_rules(union_weight)
    delta, weights = dd.gauss_legendre_delta_grid(DELTA_LOW, DELTA_HIGH, 96)
    sweep = (union_weight,) if union_weight is not None else UNION_WEIGHTS
    grids = {
        union_rule_name(w): dd.UnionTailBayesGrid(
            delta_grid=delta, delta_weights=weights, tail_size=vocab - 1,
            dirichlet_weight=float(w),
        )
        for w in sweep
    }
    grids.update({
        "bayes_shared": dd.DirichletBayesGrid(
            delta_grid=delta, delta_weights=weights,
            alpha_grid=(float("inf"),), tail_size=vocab - 1,
        ),
        # Partial pooling of the deficit, on the same working support.  The
        # released text is where this layer is worth testing: a deployed
        # deficit drifts with the context, so neither published endpoint
        # describes it, and the synthetic sweep can only show what happens when
        # the generator is told which endpoint to sit near.
        "bayes_pooled": dh.PooledDeficitGrid(
            vocabulary_size=vocab,
            delta_low=DELTA_LOW, delta_high=DELTA_HIGH,
        ),
    })
    # The wide-support arms of tab:deficit-support.  Built here so the prompt
    # bootstrap can attach a clustered standard error to them: the table used
    # to print them bare, against the manuscript's own convention.
    wide, wide_weights = dd.gauss_legendre_delta_grid(
        DELTA_LOW, WIDE_DELTA_HIGH, 96
    )
    # allow_large_delta is the point of the arm: above one half the designated
    # leading coordinate is no longer the largest under every tail draw, and
    # the table exists to show what carrying the prior there costs.
    grids["bayes_shared_wide"] = dd.DirichletBayesGrid(
        delta_grid=wide, delta_weights=wide_weights,
        alpha_grid=(float("inf"),), tail_size=vocab - 1,
        allow_large_delta=True,
    )
    for w in (0.0, 0.5):
        grids[union_rule_name(w) + "_wide"] = dd.UnionTailBayesGrid(
            delta_grid=wide, delta_weights=wide_weights,
            tail_size=vocab - 1, dirichlet_weight=float(w),
            allow_large_delta=True,
        )
    return grids


def mean_distinct_by_prefix(pivots: np.ndarray) -> np.ndarray:
    """Mean number of *distinct* pivot values within each prefix.

    Repeated skipgram contexts reuse one PRF seed, so a repeated n-gram
    reproduces the pivot exactly.  A value is counted at the prefix where it
    first appears.

    Duplicates are why Tr-GoF's power at low temperature is not monotone in the
    token count, but not by the route one might expect.  Its evidence does not
    saturate -- on Sheared-2.7B at temperature 0.3 the median watermarked
    statistic still climbs from 11.1 at 100 tokens to 20.5 at 200.  What moves
    is the empirical *null*: tied p-values are exactly the ``t/n`` jump that
    Higher Criticism is built to flag, so the null's 95th percentile inflates
    superlinearly (9.2 at 100 tokens to 23.6 at 200, against a flat ~4.8 under
    i.i.d. uniform pivots) until the cutoff overtakes the watermarked median.
    Scoring only distinct pivots restores monotonicity for Tr-GoF, and is a
    repair specific to it: the eight cumulative-sum rules do not normalise by
    ``n`` at all, and deduplicating them destroys power, because for a sum a
    repeated pivot carries repeated signal.
    """
    rounded = np.round(pivots, 12)
    counts = np.empty(rounded.shape, dtype=float)
    for index, row in enumerate(rounded):
        _, first = np.unique(row, return_index=True)
        fresh = np.zeros(row.shape[0], dtype=float)
        fresh[first] = 1.0
        counts[index] = np.cumsum(fresh)
    return counts.mean(axis=0)


def auc_score(watermarked: np.ndarray, null: np.ndarray) -> float:
    """Threshold-free separation: P(score_wm > score_null), ties counted half.

    Reported because it needs no cutoff at all.  A split-half cutoff drawn from
    250 documents has a standard deviation large enough to reorder rules whose
    Type II rates differ by less than about .03, so a ranking read off one split
    is not evidence; AUC removes the cutoff from the comparison entirely.
    """
    combined = np.concatenate([watermarked, null])
    order = combined.argsort(kind="mergesort")
    ranks = np.empty(combined.shape[0], dtype=float)
    ranks[order] = np.arange(1, combined.shape[0] + 1, dtype=float)
    # average ranks within tied blocks
    sortedv = combined[order]
    start = 0
    while start < sortedv.shape[0]:
        stop = start
        while stop + 1 < sortedv.shape[0] and sortedv[stop + 1] == sortedv[start]:
            stop += 1
        if stop > start:
            ranks[order[start : stop + 1]] = (start + stop + 2) / 2.0
        start = stop + 1
    n_wm = watermarked.shape[0]
    return float(
        (ranks[:n_wm].sum() - n_wm * (n_wm + 1) / 2.0) / (n_wm * null.shape[0])
    )


def _mcse(rate: float, n: int) -> float:
    return float(np.sqrt(max(rate * (1.0 - rate), 0.0) / n)) if n else float("nan")


def curve_rows(
    model: str,
    temperature: str,
    watermarked: np.ndarray,
    null: np.ndarray,
    grids: Mapping[str, object],
    *,
    scheme: str = "gumbel",
    vocab: int | None = None,
    rules: Sequence[str] | None = None,
) -> list[dict[str, object]]:
    """One row per (rule, prefix), calibrating each prefix independently."""
    horizon = watermarked.shape[1]
    n_null = null.shape[0]
    half = n_null // 2
    rng = np.random.default_rng(20260829)
    distinct_watermarked = mean_distinct_by_prefix(watermarked)
    distinct_null = mean_distinct_by_prefix(null)
    if rules is None:
        rules = COMPUTED_RULES if scheme == "gumbel" else INVERSE_RULE_ORDER
    def score(rule, values):
        if scheme == "gumbel":
            return score_paths(rule, values, grids)
        return inverse_score_paths(rule, values, grids, vocab)

    rows: list[dict[str, object]] = []
    for rule in rules:
        null_paths = score(rule, null)
        wat = score(rule, watermarked)

        # Type II uses the whole null arm without fitting to watermarked scores.
        # The arms remain prompt-paired. Equal realised calibration size also
        # requires no cutoff ties; continuity of a formula does not ensure this
        # for finite-precision PRF outputs. A split-half cutoff with 250
        # calibration documents has a realised level with standard
        # deviation about .02, inducing a Type II standard deviation near .03,
        # which is larger than the differences between the leading rules.  An
        # earlier version of this command ranked rules on one hard-coded split
        # and the ranking did not survive swapping the halves.
        cutoffs = np.quantile(null_paths, 1.0 - LEVEL, axis=0)
        type2 = 1.0 - (wat > cutoffs).mean(axis=0)

        # Type I is cross-fitted so it stays honest while still using every
        # document: calibrate on the other folds, evaluate on this one.
        folds = np.array_split(np.arange(n_null), CROSS_FIT_FOLDS)
        hits = np.zeros(horizon)
        for fold in folds:
            mask = np.ones(n_null, dtype=bool); mask[fold] = False
            fold_cut = np.quantile(null_paths[mask], 1.0 - LEVEL, axis=0)
            hits += (null_paths[fold] > fold_cut).sum(axis=0)
        type1 = hits / n_null

        # How much of a Type II gap is calibration noise?  Re-split repeatedly
        # and record the spread the old design was drawing from.
        replicates = np.empty((SPLIT_REPLICATES, horizon))
        for index in range(SPLIT_REPLICATES):
            pick = rng.permutation(n_null)[:half]
            rep_cut = np.quantile(null_paths[pick], 1.0 - LEVEL, axis=0)
            replicates[index] = 1.0 - (wat > rep_cut).mean(axis=0)
        split_mean = replicates.mean(axis=0)
        split_sd = replicates.std(axis=0)
        auc = np.array([
            auc_score(wat[:, i], null_paths[:, i]) for i in range(horizon)
        ])
        for index in range(horizon):
            rows.append({
                "model": model,
                "temperature": temperature,
                "scheme": scheme,
                "tokens_generated": horizon,
                "rule": rule,
                "prefix": index + 1,
                "type1": float(type1[index]),
                "type1_mcse": _mcse(float(type1[index]), n_null),
                "type2": float(type2[index]),
                "type2_mcse": _mcse(float(type2[index]), watermarked.shape[0]),
                "auc": float(auc[index]),
                "type2_split_half": float(split_mean[index]),
                "type2_split_sd": float(split_sd[index]),
                "n_calibration": int(n_null),
                "n_type1": int(n_null),
                "n_watermarked": int(watermarked.shape[0]),
                "distinct_watermarked": float(distinct_watermarked[index]),
                "distinct_null": float(distinct_null[index]),
            })
    return rows


def collect(models: Sequence[str], scratch: Path, scheme: str = "gumbel",
            union_weight: float | None = None, *, allow_legacy: bool = False,
            provenance: dict | None = None) -> list[dict[str, object]]:
    from wrong_key_null import replay_with_key

    if not models or len(set(models)) != len(models) or any(model not in MODEL_VOCAB for model in models):
        raise ValueError("models must be distinct supported model names")
    rows: list[dict[str, object]] = []
    for model in models:
        vocab = MODEL_VOCAB[model]
        cells = matched.load_cells(scratch, model, scheme=scheme, allow_legacy=allow_legacy)
        grids = build_grids(vocab, union_weight) if scheme == "gumbel" else {}
        for cell in cells:
            temperature = cell.temperature
            watermarked = (cell.watermarked["Y"].astype(float) if scheme == "gumbel"
                           else formal_inverse_pivots(cell.watermarked["U"],
                                                      cell.watermarked["eta"], vocab))
            tokens = cell.raw["tokens"]
            # Pairing, global prompt offsets, token budgets and provenance have
            # already been checked by the shared loader. No implicit truncation.
            null_gumbel, null_inverse = replay_with_key(
                cell.prompts, tokens, vocabulary_size=vocab, key=15_485_863,
                horizon=watermarked.shape[1],
            )
            null = null_gumbel if scheme == "gumbel" else null_inverse
            if provenance is not None:
                provenance[f"{model}_T{temperature}"] = cell.provenance
            rows.extend(curve_rows(
                model, temperature, watermarked, null, grids, scheme=scheme,
                vocab=vocab, rules=computed_rules(union_weight) if scheme == "gumbel" else INVERSE_RULE_ORDER,
            ))
            print(f"  {model} t{temperature}: {watermarked.shape} prefixes done", flush=True)
    return rows


def write_csv(rows: Sequence[Mapping[str, object]], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=CURVE_FIELDS)
        writer.writeheader()
        writer.writerows(rows)


def _setup_axes(ax) -> None:
    """Recessive grid and spines; the curves carry the ink."""
    ax.grid(True, linewidth=0.4, alpha=0.28, color="#9aa0a6")
    ax.set_axisbelow(True)
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    for side in ("left", "bottom"):
        ax.spines[side].set_linewidth(0.6)
        ax.spines[side].set_color("#5f6368")
    ax.tick_params(labelsize=6.2, width=0.6, color="#5f6368", length=2.6)


def _style_for(scheme: str, union_weight=None):
    if scheme == "inverse":
        return INVERSE_RULE_ORDER, RULE_LABEL_INV, RULE_COLOR_INV, RULE_DASH_INV
    if union_weight is None:
        return RULE_ORDER, RULE_LABEL, RULE_COLOR, RULE_DASH
    computed_rules(union_weight)  # validate before constructing labels
    default, selected = union_rule_name(.5), union_rule_name(union_weight)
    order = tuple(selected if rule == default else rule for rule in RULE_ORDER)
    labels, colors, dashes = dict(RULE_LABEL), dict(RULE_COLOR), dict(RULE_DASH)
    labels[selected] = UNION_RULE_LABEL.get(union_weight, f"union tail, $w={union_weight:g}$")
    colors[selected], dashes[selected] = colors[default], dashes[default]
    return order, labels, colors, dashes


def plot_prefix_grid(
    rows: Sequence[Mapping[str, object]], model: str, output_stem: Path,
    scheme: str = "gumbel", union_weight=None,
) -> None:
    """Type II against prefix length, one panel per temperature."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.lines import Line2D

    subset = [row for row in rows if row["model"] == model]
    if not subset:
        return
    order, labels_map, colors_map, dashes_map = _style_for(scheme, union_weight)
    temperatures = sorted({str(row["temperature"]) for row in subset}, key=float)
    columns = 4
    panels = len(temperatures)
    grid_rows = (panels + columns - 1) // columns
    figure_height = 2.05 * grid_rows + 1.48
    fig, axes = plt.subplots(
        grid_rows, columns,
        figsize=(7.2, figure_height),
        sharex=False, sharey=True,
    )
    axes = np.atleast_1d(axes).ravel()
    comparison_marker_drawn = False

    for index, temperature in enumerate(temperatures):
        ax = axes[index]
        _setup_axes(ax)
        ax.tick_params(labelsize=7.8, width=0.7, length=2.9)
        cell = [row for row in subset if str(row["temperature"]) == temperature]
        horizon = max(int(row["prefix"]) for row in cell)
        if horizon > SUMMARY_HORIZON:
            ax.axvline(
                SUMMARY_HORIZON, color="#6b7280", linewidth=1.0,
                linestyle=(0, (1.5, 2.0)), alpha=0.85, zorder=1,
            )
            comparison_marker_drawn = True
        for depth, rule in enumerate(reversed(order)):
            series = sorted(
                (row for row in cell if row["rule"] == rule),
                key=lambda row: int(row["prefix"]),
            )
            if not series:
                continue
            x = [int(row["prefix"]) for row in series]
            y = [float(row["type2"]) for row in series]
            dashes = dashes_map[rule]
            ax.plot(
                x, y,
                color=colors_map[rule], linewidth=1.55, zorder=2 + depth,
                dashes=dashes if dashes else (None, None),
                solid_capstyle="round", dash_capstyle="round",
            )
        ax.set_title(
            f"temperature {float(temperature):.1f}", fontsize=8.8, pad=4.0,
            color="#202124",
        )
        ax.set_ylim(-0.03, 1.03)
        ax.set_xlim(0, horizon)
        ax.set_yticks([0.0, 0.25, 0.5, 0.75, 1.0])
        if index % columns == 0:
            ax.set_ylabel("Type II error", fontsize=8.0)
        if index >= panels - columns:
            ax.set_xlabel(r"Scored prefix length $n$", fontsize=8.0)
    for ax in axes[panels:]:
        ax.set_visible(False)

    handles = [
        Line2D([0], [0], color=colors_map[rule], linewidth=1.55,
               dashes=dashes_map[rule] if dashes_map[rule] else (None, None),
               label=labels_map[rule])
        for rule in order
    ]
    legend_band = 1.30 / figure_height
    fig.legend(
        handles=handles, loc="upper center", ncol=3, fontsize=8.0,
        frameon=False, bbox_to_anchor=(0.5, legend_band * 0.65),
        handlelength=3.0, handletextpad=0.65, columnspacing=1.8,
        labelspacing=0.55, labelcolor="#202124", borderaxespad=0.0,
    )
    scheme_name = "inverse-transform" if scheme == "inverse" else "Gumbel"
    fig.suptitle(
        f"Temperature-matched {scheme_name} detection curves, {DISPLAY_MODEL[model]}",
        fontsize=10.0, y=0.988, color="#202124",
    )
    fig.text(
        0.5, 0.948,
        "Both arms generated at the matched temperature shown; 5% cutoff "
        "calibrated per prefix on the whole unwatermarked arm.",
        ha="center", va="top", fontsize=7.0, color="#5f6368",
    )
    if comparison_marker_drawn:
        fig.text(
            0.5, 0.920,
            "Vertical guides in the 200-token panels mark the common "
            f"{SUMMARY_HORIZON}-token comparison horizon.",
            ha="center", va="top", fontsize=7.0, color="#5f6368",
        )
    fig.subplots_adjust(
        top=0.855, bottom=legend_band, left=0.085, right=0.985,
        hspace=0.46, wspace=0.18,
    )
    output_stem.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_stem.with_suffix(".pdf"), bbox_inches="tight")
    fig.savefig(output_stem.with_suffix(".png"), dpi=220, bbox_inches="tight")
    plt.close(fig)


def plot_temperature_summary(
    rows: Sequence[Mapping[str, object]], output_stem: Path,
    horizon: int = SUMMARY_HORIZON, scheme: str = "gumbel", union_weight=None,
) -> None:
    """Type II against temperature at a fixed prefix -- the discriminating region."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.lines import Line2D

    models = [m for m in MODEL_VOCAB if any(row["model"] == m for row in rows)]
    if not models:
        return
    order, labels_map, colors_map, dashes_map = _style_for(scheme, union_weight)
    width = 7.2 if len(models) > 1 else 3.9
    fig, axes = plt.subplots(1, len(models), figsize=(width, 2.95), sharey=True)
    axes = np.atleast_1d(axes).ravel()
    for ax, model in zip(axes, models):
        _setup_axes(ax)
        subset = [
            row for row in rows
            if row["model"] == model and int(row["prefix"]) == horizon
        ]
        temperatures = sorted({float(row["temperature"]) for row in subset})
        for depth, rule in enumerate(reversed(order)):
            points = {
                float(row["temperature"]): float(row["type2"])
                for row in subset if row["rule"] == rule
            }
            xs = [t for t in temperatures if t in points]
            if not xs:
                continue
            dashes = dashes_map[rule]
            ax.plot(
                xs, [points[t] for t in xs],
                color=colors_map[rule], linewidth=1.35, marker="o",
                markersize=3.4, markeredgewidth=0.0, zorder=2 + depth,
                dashes=dashes if dashes else (None, None),
                solid_capstyle="round", dash_capstyle="round",
            )
        ax.set_title(DISPLAY_MODEL[model], fontsize=8, pad=4, color="#202124")
        ax.set_xlabel("sampling temperature (both arms)", fontsize=7)
        ax.set_ylim(-0.03, 1.03)
        ax.set_yticks([0.0, 0.25, 0.5, 0.75, 1.0])
    axes[0].set_ylabel(f"Type II rate at {horizon} tokens", fontsize=7)

    handles = [
        Line2D([0], [0], color=colors_map[rule], linewidth=1.35,
               dashes=dashes_map[rule] if dashes_map[rule] else (None, None),
               marker="o", markersize=3.4, markeredgewidth=0.0,
               label=labels_map[rule])
        for rule in order
    ]
    fig.legend(
        handles=handles, loc="lower center", ncol=3, fontsize=7,
        frameon=False, bbox_to_anchor=(0.5, 0.005), handlelength=2.9,
        columnspacing=1.7, labelcolor="#202124",
    )
    fig.suptitle(
        "Detection difficulty against sampling temperature",
        fontsize=9.2, y=1.0, color="#202124",
    )
    fig.subplots_adjust(top=0.82, bottom=0.34, left=0.085 if len(models) > 1 else 0.16,
                        right=0.985, wspace=0.12)
    output_stem.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_stem.with_suffix(".pdf"), bbox_inches="tight")
    fig.savefig(output_stem.with_suffix(".png"), dpi=220, bbox_inches="tight")
    plt.close(fig)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--models", default="1p3B,2p7B")
    parser.add_argument("--scheme", default="gumbel", choices=("gumbel", "inverse"))
    parser.add_argument("--union-weight", type=float, default=None,
                        help="mixing weight w on the Dirichlet block of the union tail prior")
    parser.add_argument("--scratch", type=Path, default=SCRATCH)
    parser.add_argument("--allow-legacy-archives", action="store_true",
                        help="allow only the eight SHA-allowlisted historical NPZ files without manifests")
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument(
        "--summary-horizon", type=int, default=SUMMARY_HORIZON,
        help="prefix at which the temperature-sweep summary is drawn",
    )
    parser.add_argument(
        "--curves-csv", type=Path, default=None,
        help="reuse an existing curve CSV instead of recomputing the scores",
    )
    args = parser.parse_args(argv)
    if args.summary_horizon < 1:
        parser.error("summary-horizon must be positive")
    if args.union_weight is not None:
        if args.scheme != "gumbel":
            parser.error("--union-weight applies only to Gumbel rules")
        try:
            computed_rules(args.union_weight)
        except ValueError as exc:
            parser.error(str(exc))
    input_provenance = {}

    tag = "" if args.scheme == "gumbel" else "_inverse"
    if args.union_weight is not None:
        tag += f"_w{args.union_weight:g}".replace(".", "p")
    csv_path = args.output_dir / f"temperature_prefix_curves{tag}.csv"
    if args.curves_csv is not None:
        with args.curves_csv.open(encoding="utf-8") as handle:
            rows = [dict(row) for row in csv.DictReader(handle)]
        if not rows:
            raise ValueError("curve CSV contains no rows")
        expected = set(_style_for(args.scheme, args.union_weight)[0])
        cells = {(row["model"], row["temperature"]) for row in rows}
        for model, temperature in cells:
            present = {row["rule"] for row in rows
                       if row["model"] == model and row["temperature"] == temperature}
            if not expected <= present:
                raise ValueError(f"{model} t{temperature}: curve CSV lacks configured plotted rules")
    else:
        rows = collect(args.models.split(","), args.scratch, args.scheme, args.union_weight,
                       allow_legacy=args.allow_legacy_archives, provenance=input_provenance)
        if not rows:
            print("no curves computed")
            return 1
        write_csv(rows, csv_path)
        print(f"wrote {csv_path} ({len(rows)} rows)")

    for model in dict.fromkeys(str(row["model"]) for row in rows):
        stem = args.output_dir / f"prefix_curves_matched_{model}{tag}"
        plot_prefix_grid(rows, model, stem, args.scheme, args.union_weight)
        print(f"wrote {stem}.pdf")
    stem = args.output_dir / f"temperature_sweep_matched{tag}"
    plot_temperature_summary(rows, stem, horizon=args.summary_horizon, scheme=args.scheme,
                             union_weight=args.union_weight)
    print(f"wrote {stem}.pdf")

    summary = {
        "models": sorted({str(row["model"]) for row in rows}),
        "temperatures": sorted({str(row["temperature"]) for row in rows}, key=float),
        "scheme": args.scheme,
        "rules": list(_style_for(args.scheme, args.union_weight)[0]),
        "computed_rules": list(dict.fromkeys(row["rule"] for row in rows)),
        "input_provenance": input_provenance if args.curves_csv is None else {
            "mode": "precomputed_csv", "path": str(args.curves_csv),
            "generation_manifest_validated": False},
        "max_prefix": max(int(row["prefix"]) for row in rows),
        "summary_horizon": args.summary_horizon,
        "level": LEVEL,
    }
    (args.output_dir / f"temperature_prefix_curves_summary{tag}.json").write_text(
        json.dumps(summary, indent=2, sort_keys=True)
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
